services:
  mock-trade-core:
    build: ./mock-trade-core
    ports:
      - "50051:50051"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  trade-ping:
    build: ./trade-ping
    depends_on:
      - mock-trade-core
      - redis
    environment:
      REDIS_HOST: redis
      TRADE_CORE_HOST: mock-trade-core
      TRADE_CORE_PORT: 50051
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
